on: [push, pull_request]
name: Test
jobs:
  testWithTox:
    name: Test with tox
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: njzjz/gh-action-tox@refactor
      with:
        python-version: "3.11"
        plugins: "tox-gh-actions"
    - uses: codecov/codecov-action@v3
